# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm ci
    - run: npm run build --if-present

    - run: npm test
    - run: |
          git config user.email "automation@canariatechnologies.com"
          git config user.name "automation"
          git fetch
          git checkout publish || git checkout --orphan publish  
          shopt -s extglob 
          rm -rf !(".git"|"build") .!(""|"."|"git")
          mv build/* . 
          rm -rf build
          git add .
          git commit -m "Publish build"
          git pull --set-upstream origin publish
          git push origin publish
